#!/usr/bin/env tsx
/**
 * Regenerates the auto-generated metrics block in docs/STATE.md from live repo state.
 * Run after adding/removing courses, lessons, endpoints, or DB tables.
 *
 *   npx tsx scripts/snapshot-platform.ts
 */

import { execSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(SCRIPT_DIR, "..");
const STATE_PATH = join(REPO_ROOT, "docs/STATE.md");
const BEGIN = "<!-- BEGIN:AUTO-METRICS -->";
const END = "<!-- END:AUTO-METRICS -->";

function countFiles(pattern: string, baseDir: string): number {
  try {
    const output = execSync(`find '${baseDir}' -type f -name '${pattern}' 2>/dev/null | wc -l`, {
      cwd: REPO_ROOT,
      encoding: "utf8",
    });
    return Number.parseInt(output.trim(), 10);
  } catch {
    return 0;
  }
}

function countRouteFiles(): number {
  try {
    const output = execSync(
      `find app/api -type f \\( -name 'route.ts' -o -name 'route.tsx' -o -name 'route.js' \\) 2>/dev/null | wc -l`,
      { cwd: REPO_ROOT, encoding: "utf8" },
    );
    return Number.parseInt(output.trim(), 10);
  } catch {
    return 0;
  }
}

function countDbTables(): number {
  try {
    const schema = readFileSync(join(REPO_ROOT, "lib/db/schema.ts"), "utf8");
    return (schema.match(/pgTable\s*\(/g) ?? []).length;
  } catch {
    return 0;
  }
}

function countDirectories(baseDir: string, depth = 1): number {
  try {
    const output = execSync(
      `find '${baseDir}' -mindepth ${depth} -maxdepth ${depth} -type d 2>/dev/null | wc -l`,
      { cwd: REPO_ROOT, encoding: "utf8" },
    );
    return Number.parseInt(output.trim(), 10);
  } catch {
    return 0;
  }
}

const metrics = {
  lessons: countFiles("lesson-*.md", "server/data/content"),
  quizzes: countFiles("*.json", "server/data/quizzes"),
  assessments: countFiles("*.json", "server/data/assessments"),
  apiEndpoints: countRouteFiles(),
  dbTables: countDbTables(),
  tracks: countDirectories("server/data/content", 1),
  interactiveComponents: countFiles("*.tsx", "app/(default)/academy/components"),
  sharedComponents: countFiles("*.tsx", "components"),
  typeDefinitions: countFiles("*.ts", "types"),
};

const today = new Date().toISOString().slice(0, 10);

const block = `${BEGIN}
> **Auto-generated by \`scripts/snapshot-platform.ts\` on ${today}. Do not hand-edit.**

| Asset | Count | Source |
|-------|-------|--------|
| Content tracks | ${metrics.tracks} | \`server/data/content/\` |
| Lesson MDX files | ${metrics.lessons} | \`server/data/content/**/lesson-*.md\` |
| Quiz JSON files | ${metrics.quizzes} | \`server/data/quizzes/**/*.json\` |
| Clinical assessments | ${metrics.assessments} | \`server/data/assessments/*.json\` |
| API endpoints | ${metrics.apiEndpoints} | \`app/api/**/route.{ts,tsx,js}\` |
| Database tables | ${metrics.dbTables} | \`lib/db/schema.ts\` (pgTable calls) |
| Interactive lesson components | ${metrics.interactiveComponents} | \`app/(default)/academy/components/\` |
| Shared UI components | ${metrics.sharedComponents} | \`components/\` |
| Type definition files | ${metrics.typeDefinitions} | \`types/\` |
${END}`;

const state = readFileSync(STATE_PATH, "utf8");
const beginIdx = state.indexOf(BEGIN);
const endIdx = state.indexOf(END);

let next: string;
if (beginIdx !== -1 && endIdx !== -1) {
  next = `${state.slice(0, beginIdx)}${block}${state.slice(endIdx + END.length)}`;
} else {
  next = `${state.trimEnd()}\n\n---\n\n## Live Platform Metrics\n\n${block}\n`;
}

writeFileSync(STATE_PATH, next);

console.log(`Updated ${STATE_PATH}`);
console.log(JSON.stringify(metrics, null, 2));
