#!/usr/bin/env bash
# provision-04-app-env.sh — populate the env var string on both apps
# (gtm + dwa) via application.saveEnvironment.
#
# Reads:
#   .env.local          — SOLOFAME_POSTGRES_PASSWORD, SOLOFAME_REDIS_PASSWORD
#                         (generated by provision-01). Also reads existing
#                         SOLOFAME_APP_{GTM,DWA}_ADMIN_API_SECRET /
#                         SOLOFAME_APP_GTM_ENCRYPTION_KEY if present — only
#                         generates fresh if missing.
#   infra/dokploy/state.json — applicationIds for gtm + dwa
#
# Writes:
#   .env.local — persists any newly-generated secrets (so re-runs are stable)
#   Dokploy   — updates each app's env string via saveEnvironment
#
# What this script does NOT set (you add these in Dokploy UI before first deploy):
#   OPENROUTER_API_KEY / OPENAI_API_KEY   — pick one, paste the real key
#   POLAR_ACCESS_TOKEN + POLAR_SUCCESS_URL (gtm only)
#   RESEND_API_KEY
#   ADMIN_EMAILS                           (gtm only) — comma-separated admin addrs
#   NEXT_PUBLIC_APP_URL                    — set to the app's real URL once domain lands
#   Any other provider-specific keys in docs/deployment-env.md
#
# Placeholder TODO lines are written for the third-party keys so you see
# them in the Dokploy UI as "empty fields to fill in."
#
# Flags:
#   --dry-run
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
DK="$HERE/dk"
STATE_FILE="$ROOT/infra/dokploy/state.json"
ENV_LOCAL="$ROOT/.env.local"

DRY_RUN=0
for a in "$@"; do
  case "$a" in
    --dry-run) DRY_RUN=1 ;;
    *) echo "unknown arg: $a" >&2; exit 2 ;;
  esac
done

log()  { printf '\033[36m[provision-04]\033[0m %s\n' "$*" >&2; }
ok()   { printf '\033[32m  ✓\033[0m %s\n' "$*" >&2; }
plan() { printf '\033[33m  »\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[31m  ✗\033[0m %s\n' "$*" >&2; exit 1; }

gen_secret() {
  python3 -c 'import secrets; print(secrets.token_hex(32))'
}

get_env() {
  [ -f "$ENV_LOCAL" ] || return 1
  local line; line="$(grep -E "^$1=" "$ENV_LOCAL" | tail -n1 || true)"
  [ -n "$line" ] || return 1
  printf '%s\n' "${line#*=}"
}

put_env() {
  local key="$1" val="$2"
  touch "$ENV_LOCAL"
  KEY="$key" VAL="$val" FILE="$ENV_LOCAL" python3 <<'PY'
import os, re
path = os.environ['FILE']; key = os.environ['KEY']; val = os.environ['VAL']
try: lines = open(path).read().splitlines()
except FileNotFoundError: lines = []
pat = re.compile(rf'^\s*{re.escape(key)}\s*=')
kept = [ln for ln in lines if not pat.match(ln)]
kept.append(f'{key}={val}')
open(path, 'w').write('\n'.join(kept) + '\n')
PY
}

get_state() {
  [ -f "$STATE_FILE" ] || die "state.json missing — run provision-01 + 03 first"
  KEY="$1" FILE="$STATE_FILE" python3 <<'PY'
import json, os
d = json.load(open(os.environ['FILE']))
print(d.get(os.environ['KEY'], '') or '')
PY
}

call() {
  local method="$1" path="$2" body="${3:-}"
  if [ "$DRY_RUN" = "1" ] && [ "$method" != "GET" ]; then
    plan "$method $path ${body:+<$(printf '%s' "$body" | head -c 200)...>}"
    echo '{}'
    return 0
  fi
  if [ -n "$body" ]; then "$DK" "$method" "$path" "$body"; else "$DK" "$method" "$path"; fi
}

GTM_ID="$(get_state gtmApplicationId)"
DWA_ID="$(get_state dwaApplicationId)"
[ -n "$GTM_ID" ] || die "no gtmApplicationId — run provision-03 first"
[ -n "$DWA_ID" ] || die "no dwaApplicationId — run provision-03 first"

POSTGRES_PW="$(get_env SOLOFAME_POSTGRES_PASSWORD || die 'SOLOFAME_POSTGRES_PASSWORD missing — run provision-01')"
REDIS_PW="$(get_env SOLOFAME_REDIS_PASSWORD     || die 'SOLOFAME_REDIS_PASSWORD missing — run provision-01')"

GTM_ADMIN_SECRET="$(get_env SOLOFAME_APP_GTM_ADMIN_API_SECRET || gen_secret)"
DWA_ADMIN_SECRET="$(get_env SOLOFAME_APP_DWA_ADMIN_API_SECRET || gen_secret)"
GTM_ENCRYPTION_KEY="$(get_env SOLOFAME_APP_GTM_ENCRYPTION_KEY || gen_secret)"

put_env SOLOFAME_APP_GTM_ADMIN_API_SECRET "$GTM_ADMIN_SECRET"
put_env SOLOFAME_APP_DWA_ADMIN_API_SECRET "$DWA_ADMIN_SECRET"
put_env SOLOFAME_APP_GTM_ENCRYPTION_KEY   "$GTM_ENCRYPTION_KEY"

# Docker Swarm internal service names for the sidecars — provision-01 created
# them as postgres-primary / redis-primary, so they resolve on the overlay.
DATABASE_URL="postgres://app_user:${POSTGRES_PW}@postgres-primary:5432/solofame"
REDIS_URL="redis://:${REDIS_PW}@redis-primary:6379"

# Build the per-app env string. Blank lines + comments are legal in Dokploy's
# env field (it parses like a .env file). Third-party keys land as empty
# lines the user fills in via the Dokploy UI.
build_env_dwa() {
  cat <<EOF
# --- infrastructure (set by provision-04) ---
DATABASE_URL=$DATABASE_URL
REDIS_URL=$REDIS_URL
PLATFORM_DATABASE_URL=$DATABASE_URL
ADMIN_API_SECRET=$DWA_ADMIN_SECRET

# --- platform wiring ---
TENANT_ROOT_DOMAINS=
MANIFEST_VERTICAL_ROOT=/app/verticals
NEXT_PUBLIC_APP_NAME=dwa
NEXT_PUBLIC_APP_VERSION=0.1.0

# --- third-party (fill in via Dokploy UI before first real traffic) ---
NEXT_PUBLIC_APP_URL=
OPENROUTER_API_KEY=
OPENAI_API_KEY=
MAIA_URL=
AI_MODEL_COACHING=
FLARUM_URL=
FLARUM_PUBLIC_URL=
FLARUM_API_KEY=
EOF
}

build_env_gtm() {
  cat <<EOF
# --- infrastructure (set by provision-04) ---
DATABASE_URL=$DATABASE_URL
REDIS_URL=$REDIS_URL
PLATFORM_DATABASE_URL=$DATABASE_URL
ADMIN_API_SECRET=$GTM_ADMIN_SECRET
ENCRYPTION_KEY=$GTM_ENCRYPTION_KEY

# --- platform wiring ---
TENANT_ROOT_DOMAINS=
MANIFEST_VERTICAL_ROOT=/app/verticals
NEXT_PUBLIC_APP_NAME=gtm
NEXT_PUBLIC_APP_VERSION=0.1.0

# --- third-party (fill in via Dokploy UI before first real traffic) ---
NEXT_PUBLIC_APP_URL=
ADMIN_EMAILS=
OPENROUTER_API_KEY=
OPENAI_API_KEY=
ANTHROPIC_API_KEY=
AI_PROVIDER=
POLAR_ACCESS_TOKEN=
POLAR_SUCCESS_URL=
POLAR_WEBHOOK_SECRET=
POLAR_MODE=sandbox
NEXT_PUBLIC_POLAR_BOOK_PRODUCT_ID=
RESEND_API_KEY=
NOTION_CLIENT_ID=
NOTION_CLIENT_SECRET=
EOF
}

push_env() {
  local name="$1" app_id="$2" envstr="$3" build_args="$4"
  log "saveEnvironment for $name"
  local body
  body="$(APP="$app_id" ENV="$envstr" BA="$build_args" python3 <<'PY'
import json, os
print(json.dumps({
  "applicationId": os.environ["APP"],
  "env": os.environ["ENV"],
  "buildArgs": os.environ["BA"],
  "buildSecrets": "",
  "createEnvFile": False,
}))
PY
)"
  call POST /api/application.saveEnvironment "$body" > /dev/null
  ok "  env + buildArgs updated"
}

push_env "gtm" "$GTM_ID" "$(build_env_gtm)" "APP=gtm"
push_env "dwa" "$DWA_ID" "$(build_env_dwa)" "APP=dwa"

log "done — next steps:"
log "  1. Dokploy UI → each app → Environment tab: fill in the blank"
log "     third-party key lines (OPENROUTER_API_KEY, POLAR_*, etc.)."
log "     NEXT_PUBLIC_APP_URL + TENANT_ROOT_DOMAINS can stay blank"
log "     until domains land in provision-05."
log "  2. Click Deploy on each app. First build is server-side — iterate"
log "     as commits on main if the Dockerfile hits unfamiliar ground."
